export const API_ENDPOINTS = {
	USERS: '/users',
	PRODUCTS: '/products',
	STORE: '/stores',
	PRODUCTS_SEARCH: '/products/search',
	LOGIN: '/auth/login',
	LOGIN_GOOGLE: '/auth/google',
	LOGIN_GITHUB: '/auth/github',
	REGISTER: '/auth/register',
	LOGOUT: '/auth/logout',
	PASS_RESET_REQUEST: '/auth/password/reset',
	PASS_RESET_CONFIRM: '/auth/password/reset/confirm',
	PASS_CHANGE: '/users/password/change',
	VERIFY_OTP: '/auth/verify-otp',
	PROFILE: '/users/profile',
	REFRESH: '/refresh',
	SETTINGS: '/settings',
};

export const APP_ROUTES = {
	HOME: '/',
	COLLECTIONS: '/collections',
	STORES: '/stores',
	STORE: '/stores',
	CREATE_STORE: '/stores/create',
	CART: '/cart',
	PROFILE: '/profile',
	SETTINGS: '/settings',
	CONTACT: '/contact',
	PRIVACY_POLICY: '/privacy_policy',
	TERMS_CONDITIONS: '/terms_conditions',
	NEW: '/new',
	LOGIN: '/login',
	REGISTER: '/register',
	PASS_RESET: '/password/reset',
	PASS_CHANGE: '/password/change',
	COSMETICS: '/category/cosmeticsc',
	ELECTRONICS: '/category/electronics',
	APPARELS: '/category/apparels',
	HOME_APPLIANCES: '/category/home_appliances',
	FURNITURES: '/category/furnitures',
	BOOKS: '/category/books',
};

export const APP_NAME = 'Marketiqo';
